Refactor linux bash script to use new Java CLI

diff --git a/bin/grakn b/bin/grakn
--- a/bin/grakn
+++ b/bin/grakn
@@ -44,37 +44,41 @@ exit_if_java_not_found() {
 
 exit_if_java_not_found
 
-if [ -z "$1" ]; then
-    echo "Missing argument. Possible commands are:"
-    echo "  Server:          grakn server [--help]"
-    echo "  Console:         grakn console [--help]"
-    exit 1
-elif [ "$1" = "console" ]; then
-    if [ -f "${CONSOLE_JAR_FILENAME}" ]; then
-        SERVICE_LIB_CP="console/services/lib/*"
-        CLASSPATH="${GRAKN_HOME}/${SERVICE_LIB_CP}:${GRAKN_HOME}/console/conf/"
-        java ${CONSOLE_JAVAOPTS} -cp "${CLASSPATH}" -Dgrakn.dir="${GRAKN_HOME}" grakn.console.GraknConsole "$@"
-    else
-        echo "Grakn Core Console is not included in this Grakn distribution."
-        echo "You may want to install Grakn Core Console or Grakn Core (all)."
-        exit 1
-    fi
-elif [[ "$1" = "server" ]] || [[ "$1" = "version" ]]; then
-    if [[ -f "${SERVER_JAR_FILENAME}" ]]; then
-        SERVICE_LIB_CP="server/services/lib/*"
-        CLASSPATH="${GRAKN_HOME}/${SERVICE_LIB_CP}:${GRAKN_HOME}/server/conf/"
-        java ${GRAKN_DAEMON_JAVAOPTS} -cp "${CLASSPATH}" -Dgrakn.dir="${GRAKN_HOME}" -Dgrakn.conf="${GRAKN_HOME}/${GRAKN_CONFIG}" -Dstorage.javaopts="${STORAGE_JAVAOPTS}" -Dserver.javaopts="${SERVER_JAVAOPTS}" grakn.core.daemon.GraknDaemon $@
-    else
-        echo "Grakn Core Server is not included in this Grakn distribution."
-        echo "You may want to install Grakn Core Server or Grakn Core (all)."
-        exit 1
-    fi
-else
-    echo "Invalid argument: $1. Possible commands are: "
-    echo "  Server:          grakn server [--help]"
-    echo "  Console:         grakn console [--help]"
-    exit 1
-fi
+# if [ -z "$1" ]; then
+#     echo "Missing argument. Possible commands are:"
+#     echo "  Server:          grakn server [--help]"
+#     echo "  Console:         grakn console [--help]"
+#     exit 1
+# elif [ "$1" = "console" ]; then
+#     if [ -f "${CONSOLE_JAR_FILENAME}" ]; then
+#         SERVICE_LIB_CP="console/services/lib/*"
+#         CLASSPATH="${GRAKN_HOME}/${SERVICE_LIB_CP}:${GRAKN_HOME}/console/conf/"
+#         java ${CONSOLE_JAVAOPTS} -cp "${CLASSPATH}" -Dgrakn.dir="${GRAKN_HOME}" grakn.console.GraknConsole "$@"
+#     else
+#         echo "Grakn Core Console is not included in this Grakn distribution."
+#         echo "You may want to install Grakn Core Console or Grakn Core (all)."
+#         exit 1
+#     fi
+# elif [[ "$1" = "server" ]] || [[ "$1" = "version" ]]; then
+#     if [[ -f "${SERVER_JAR_FILENAME}" ]]; then
+#         SERVICE_LIB_CP="server/services/lib/*"
+#         CLASSPATH="${GRAKN_HOME}/${SERVICE_LIB_CP}:${GRAKN_HOME}/server/conf/"
+#         java ${GRAKN_DAEMON_JAVAOPTS} -cp "${CLASSPATH}" -Dgrakn.dir="${GRAKN_HOME}" -Dgrakn.conf="${GRAKN_HOME}/${GRAKN_CONFIG}" -Dstorage.javaopts="${STORAGE_JAVAOPTS}" -Dserver.javaopts="${SERVER_JAVAOPTS}" grakn.core.daemon.GraknDaemon $@
+#     else
+#         echo "Grakn Core Server is not included in this Grakn distribution."
+#         echo "You may want to install Grakn Core Server or Grakn Core (all)."
+#         exit 1
+#     fi
+# else
+#     echo "Invalid argument: $1. Possible commands are: "
+#     echo "  Server:          grakn server [--help]"
+#     echo "  Console:         grakn console [--help]"
+#     exit 1
+# fi
+
+SERVICE_LIB_CP="cli/services/lib/*"
+CLASSPATH="${GRAKN_HOME}/${SERVICE_LIB_CP}:${GRAKN_HOME}/cli/conf/"
+java ${GRAKN_JAVAOPTS} -cp "${CLASSPATH}" -Dgrakn.dir="${GRAKN_HOME}" -Dgrakn.conf="${GRAKN_HOME}/${GRAKN_CONFIG}" -Dstorage.javaopts="${STORAGE_JAVAOPTS}" -Dserver.javaopts="${SERVER_JAVAOPTS}" grakn.core.cli.GraknCli "$@"
 
 exit $?
 
